// SPDX-License-Identifier: Apache-2.0
pragma solidity 0.8.28;

import {ICrossChainVerifier} from "interfaces/ICrossChainEntrypoint.sol";

/**
 * @title CrossChainBurnVerifier Stub
 * @notice A placeholder verifier that compiles out-of-the-box for tests and local setups.
 *         Should be replaced by the final Solidity contract generated by snarkjs
 *         after executing the trusted setup ceremony on crossChainBurn.circom.
 */
contract CrossChainBurnVerifier is ICrossChainVerifier {
  /**
   * @notice A mock proof verification that always succeeds.
   * @inheritdoc ICrossChainVerifier
   */
  function verifyProof(
    uint256[2] memory,
    uint256[2][2] memory,
    uint256[2] memory,
    uint256[9] memory
  ) external pure override returns (bool _valid) {
    _valid = true;
  }
}
